version: "3.8"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 8080:8080
    container_name: jenkins
    volumes:
      - ~/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
#http://jenkins-config:8080/
